# Generated by Django 4.2.6 on 2023-10-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='question_text',
            new_name='query_text',
        ),
    ]
