# Generated by Django 4.2.6 on 2023-10-12 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_question_text_query_query_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
